
import {  MoodListTypeItem } from '../types'



export const MoodList: Array<MoodListTypeItem> = [
  {
    time: '2024-06-22',
    user_title: '今天终于找到组织啦！ 希望下次还能一起在',
    imageList: [
      $r('app.media.girl6'),
      $r('app.media.girl5'),
      $r('app.media.girl2'),
      $r('app.media.girl3'),
    ]
  },
  {
    time: '2024-06-22',
    user_title: '今天终于找到组织啦！ 希望下次还能一起在钴铬合金76677',
    imageList: [
      $r('app.media.girl6'),
      $r('app.media.girl5'),
      $r('app.media.girl2'),
      $r('app.media.girl3'),
    ]
  }
]

