
import { FriendListType, ChatListItemType } from '../types'

export const newFriendList: Array<FriendListType> = [
  {
    uri: $r('app.media.girl1'),
    desc: '新配对'
  },
  {
    uri: $r('app.media.girl2'),
    desc: '10Km'
  },
  {
    uri: $r('app.media.girl3'),
    desc: '新配对',
    needCloud: true
  },
]

export const chatList: Array<ChatListItemType> = [
  {
    uri: $r('app.media.girl1'),
    nickname: '糊锅玉米扒而',
    lastMsg: '这边有活动，美女来参加吗',
    time: '04/10',
    online: false,
    needCloud: true
  },
  {
    uri: $r('app.media.girl3'),
    nickname: '77啊',
    lastMsg: '这边有活动，美女来参加吗',
    time: '04/10',
    online: false
  },
  {
    uri: $r('app.media.girl2'),
    nickname: 'U度是的是的',
    lastMsg: '这边有活动，美女来参加吗',
    time: '04/10',
    online: true
  },
  {
    uri: $r('app.media.girl4'),
    nickname: '卡扣式肯定是',
    lastMsg: '这边有活动，美女来参加吗',
    time: '04/10',
    online: false,
    needCloud: true
  },
  {
    uri: $r('app.media.girl3'),
    nickname: '糊锅玉米扒而',
    lastMsg: '这边有活动，美女来参加吗',
    time: '04/10',
    online: false,
  },
  {
    uri: $r('app.media.girl4'),
    nickname: '苹果',
    lastMsg: '这边有活动，美女来参加吗',
    time: '04/10',
    online: false
  },
  {
    uri: $r('app.media.girl5'),
    nickname: '测试',
    lastMsg: '这边有活动，美女来参加吗',
    time: '04/10',
    online: true
  },
  {
    uri: $r('app.media.girl6'),
    nickname: '库房地方的',
    lastMsg: '这边有活动，美女来参加吗',
    time: '04/10',
    online: false,
  },
]