import { StrangePersonType } from '../types'

export const StrangePersonList: StrangePersonType[] = [
  {
    uri: $r('app.media.girl1'),
    name: '哈哈哈哈哈',
    address: '海淀区',
    constellation: '水瓶座',
    gender: 1,
    bodyHeight: 166,
    distance: 32.22,
    age: 22
  },
  {
    uri: $r('app.media.girl2'),
    name: '哈哈哈哈哈2',
    address: '海淀区',
    constellation: '水瓶座',
    gender: 2,
    bodyHeight: 166,
    distance: 32.22,
    age: 22
  },
  {
    uri: $r('app.media.girl3'),
    name: '哈哈哈哈哈3',
    address: '海淀区',
    constellation: '水瓶座',
    gender: 1,
    bodyHeight: 166,
    distance: 32.22,
    age: 23
  },
  {
    uri: $r('app.media.girl4'),
    name: '哈哈哈哈哈4',
    address: '海淀区',
    constellation: '水瓶座',
    gender: 2,
    bodyHeight: 166,
    distance: 32.22,
    age: 28
  },

]

export const StrangePersonLisst: StrangePersonType[] = [
  {
    uri: $r('app.media.girl1'),
    name: '哈哈哈哈哈',
    address: '海淀区',
    constellation: '水瓶座',
    gender: 1,
    bodyHeight: 166,
    distance: 32.22,
    age: 22
  },
  {
    uri: $r('app.media.girl2'),
    name: '哈哈哈哈哈2',
    address: '海淀区',
    constellation: '水瓶座',
    gender: 2,
    bodyHeight: 166,
    distance: 32.22,
    age: 22
  },
  {
    uri: $r('app.media.girl3'),
    name: '哈哈哈哈哈3',
    address: '海淀区',
    constellation: '水瓶座',
    gender: 1,
    bodyHeight: 166,
    distance: 32.22,
    age: 23
  },
  {
    uri: $r('app.media.girl4'),
    name: '哈哈哈哈哈4',
    address: '海淀区',
    constellation: '水瓶座',
    gender: 2,
    bodyHeight: 166,
    distance: 32.22,
    age: 28
  },

]

export const userTagList: Array<string> = [
  '认识朋友', '我喜欢美国电影', '喜欢足球', '台球', '166cm'
]